databases:
  - name: everest
    databaseName: everest_db_bv9h
    user: everest_user

services:
  - type: web
    name: everest_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: everest_db_bv9h
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false